addons:
  postgresql: 9.5
after_success:
  - bundle exec codeclimate-test-reporter
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database upload_app_test;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.3.1
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rubocop
services:
  - redis-server
